'''
3
4 2 5 1 7
3 1 9 4 5
9 8 1 2 3
8 1 9 3 4
7 2 3 4 8
1 9 2 5 7
6 5 2 3 4
5 1 9 2 8
2 9 3 1 4
'''

In [9]:
import numpy as np

In [10]:
N = int(input())

 3


In [11]:
like_list = [0 for i in range(N*N + 1)] # 인덱스(학생 번호)별로 좋아하는 사람 목록, 0번은 없으므로 비움

In [12]:
like_list

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [13]:
order_list = [] # 학생 자리 지정 순서

In [14]:
for i in range(N*N):
    input_list = list(map(int, input().split()))
    order_list.append(input_list[0])
    like_list[input_list[0]] = input_list[1:]

 4 2 5 1 7
 3 1 9 4 5
 9 8 1 2 3
 8 1 9 3 4
 7 2 3 4 8
 1 9 2 5 7
 6 5 2 3 4
 5 1 9 2 8
 2 9 3 1 4


In [15]:
order_list

[4, 3, 9, 8, 7, 1, 6, 5, 2]

In [16]:
like_list

[0,
 [9, 2, 5, 7],
 [9, 3, 1, 4],
 [1, 9, 4, 5],
 [2, 5, 1, 7],
 [1, 9, 2, 8],
 [5, 2, 3, 4],
 [2, 3, 4, 8],
 [1, 9, 3, 4],
 [8, 1, 2, 3]]

In [17]:
like_list[2]

[9, 3, 1, 4]

In [605]:
# 전역변수의 2차원 맵 생성(check, data)
# for i in range(N):
data_map = np.array([[0 for i in range(N+1)] for j in range(N+1)]) # 학생 지정 자리 저장

check_map = np.array([])
for i in range(N+1):
    for j in range(N+1):
        if i==0 or j==0:
            check_map = np.append(check_map, [0]) # 조회 함 (0행 또는 0열의 위치는 0으로 표기)
        else:
            check_map = np.append(check_map, [1]) # 조회 안함
            
check_map = np.reshape(check_map, (N+1,N+1))

In [606]:
check_map

array([[0., 0., 0., 0.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.]])

In [607]:
data_map

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## 1. 자리 함수

In [645]:
# def location(num):

In [646]:
order_list

[4, 3, 9, 8, 7, 1, 6, 5, 2]

In [647]:
num = 3

In [648]:
# 지역변수의 2차원 맵 생성
count_like_map = np.array([[0 for i in range(N+1)] for j in range(N+1)]) # 인접 위치에 좋아하는 학생 수
count_vacant_map = np.array([[0 for i in range(N+1)] for j in range(N+1)]) # 인접 위치에 빈 자리 수

In [649]:
count_like_map

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [650]:
count_vacant_map

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

#### 1) 빈칸 중에 선호 학생이 인접 칸에 많은 위치

In [651]:
di = [-1, 1, 0, 0]
dj = [0, 0, -1, 1]

In [652]:
for i in range(1, N+1):
    for j in range(1, N+1):           
        count_like = 0 # 인접 칸의 좋아하는 학생 수
        count_vacant = 0 # 인접 칸의 빈칸 수
        
        # 인접 칸 탐색
        for k in range(4):
            ni = i + di[k]
            nj = j + dj[k]
            
            # 데이터 범위 벗어나면 무시
            if(ni>N or ni<1 or nj>N or nj<1):
                continue
            
            adj_num = data_map[ni][nj] # 인접 칸의 좋아하는 학생 번호
            
            # 자리를 배치할 학생 번호(num)의 선호 리스트에 있는지 조회
            count_like   += adj_num in like_list[num] # 인접 칸의 좋아하는 학생 수 합
            count_vacant += check_map[ni][nj] == 1 # 인접 칸의 빈자리 수 합
            
        count_like_map[i][j]   = count_like # 좋아하는 학생 수 기록
        count_vacant_map[i][j] = count_vacant # 빈칸 수 기록

In [653]:
check_map

array([[0., 0., 0., 0.],
       [0., 1., 1., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 1.]])

In [655]:
count_like_map

array([[0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 1],
       [0, 0, 1, 0]])

In [659]:
if(sum(np.ravel(count_like_map, order='C')) == 0):
    tmp = check_map + count_like_map

False

In [629]:
# 1번 조건 : 비어있는 칸 중에서 좋아하는 학생이 인접한 칸에 가장 많은 칸으로 자리를 정한다.
tmp = check_map + count_like_map

In [630]:
tmp

array([[0., 0., 0., 0.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.]])

In [631]:
np.ravel(tmp, order='C') != 0

array([False, False, False, False, False,  True,  True,  True, False,
        True,  True,  True, False,  True,  True,  True])

In [632]:
np.where(np.ravel(tmp, order='C') != 0)[0][0]

5

In [633]:
# 원소 개수 == 1
if(np.count_nonzero(np.ravel(tmp, order='C') != 0) == 1):
    final_index = np.where(np.ravel(tmp, order='C') != 0)[0][0]
#     break

In [634]:
# 2번 조건 : 1을 만족하는 칸이 여러 개이면, 인접한 칸 중에서 비어있는 칸이 가장 많은 칸으로 자리를 정한다.

In [636]:
tmp2 = tmp * count_vacant_map

In [637]:
tmp2

array([[0., 0., 0., 0.],
       [0., 2., 3., 2.],
       [0., 3., 4., 3.],
       [0., 2., 3., 2.]])

In [638]:
# 3번 조건 : 2를 만족하는 칸도 여러 개인 경우에는 행의 번호가 가장 작은 칸으로, 
# 그러한 칸도 여러 개이면 열의 번호가 가장 작은 칸으로 자리를 정한다.

In [639]:
final_index = np.argmax(tmp2)

In [640]:
final_index

10

In [641]:
# 최종의 행, 열
fi = final_index // (N + 1)# 행
fj = final_index % (N + 1) # 열

In [642]:
data_map[fi][fj] = num # 자리 배치 기록
check_map[fi][fj] = 0 # 조회 기록

In [643]:
data_map

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 0]])

In [644]:
check_map

array([[0., 0., 0., 0.],
       [0., 1., 1., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 1.]])

In [544]:
data_map[0][0] = 0

In [545]:
check_map[0][0] = 0

In [463]:
data_map

array([[0, 0, 0, 0],
       [0, 9, 3, 0],
       [0, 8, 4, 7],
       [0, 0, 0, 0]])

## 2. 만족도 함수

In [639]:
data_map

array([[0, 0, 0, 0],
       [0, 9, 3, 2],
       [0, 8, 4, 7],
       [0, 5, 6, 1]])

In [640]:
like_list

[0,
 [9, 2, 5, 7],
 [9, 3, 1, 4],
 [1, 9, 4, 5],
 [2, 5, 1, 7],
 [1, 9, 2, 8],
 [5, 2, 3, 4],
 [2, 3, 4, 8],
 [1, 9, 3, 4],
 [8, 1, 2, 3]]

In [641]:
# 지역변수의 2차원 맵 생성
for i in range(N):
    count_like_map = np.array([[0 for i in range(N+1)] for j in range(N+1)]) # 인접 위치에 좋아하는 학생 수
    count_vacant_map = np.array([[0 for i in range(N+1)] for j in range(N+1)]) # 인접 위치에 빈 자리 수

In [642]:
for i in range(1, N+1):
    for j in range(1, N+1):
        
        # 현재 고려할 학생 번호
        num = data_map[i][j]
            
        count_like = 0 # 인접 칸의 좋아하는 학생 수
        count_vacant = 0 # 인접 칸의 빈칸 수
        
        # 인접 칸 탐색
        for k in range(4):
            ni = i + di[k]
            nj = j + dj[k]
            
            # 데이터 범위 벗어나면 무시
            if(ni>N or ni<1 or nj>N or nj<1):
                continue
            
            adj_num = data_map[ni][nj] # 인접 칸의 좋아하는 학생 번호
            
            # 자리를 배치할 학생 번호(num)의 선호 리스트에 있는지 조회
            count_like   += adj_num in like_list[num] # 인접 칸의 좋아하는 학생 수 합
            count_vacant += check_map[ni][nj] == 1 # 인접 칸의 빈자리 수 합
            
        count_like_map[i][j]   = count_like # 좋아하는 학생 수 기록
        count_vacant_map[i][j] = count_vacant # 빈칸 수 기록

In [643]:
count_like_map

array([[0, 0, 0, 0],
       [0, 2, 2, 1],
       [0, 2, 1, 2],
       [0, 1, 2, 1]])

In [646]:
satis_list = np.ravel(count_like_map, order='C')

In [647]:
satis_list

array([0, 0, 0, 0, 0, 2, 2, 1, 0, 2, 1, 2, 0, 1, 2, 1])

In [665]:
number, count = np.unique(satis_list, return_counts=True)

In [666]:
satis_dict = dict(zip(number, count))

In [667]:
satis_dict

{0: 7, 1: 4, 2: 5}

In [668]:
number = np.array([0,1,2,3,4])
point = np.array([0,1,10,100,1000])
score_dict = dict(zip(number, point))

In [669]:
score_dict

{0: 0, 1: 1, 2: 10, 3: 100, 4: 1000}

In [674]:
final_point = 0
for i in satis_dict:
    print(i)
    final_point += satis_dict[i] * score_dict[i]

0
1
2


In [675]:
final_point

54